//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UserService
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserData
    {
        public int PlayerId { get; set; }
        public string UserName { get; set; }
        public string Password { get; set; }
        public int Lira { get; set; }
        public int CheeseCount { get; set; }
        public int SauceCount { get; set; }
        public int MeatCount { get; set; }
        public int PastaCount { get; set; }
        public int ClickUpgrade { get; set; }
        public Nullable<System.DateTime> LastLogin { get; set; }
        public int LPS { get; set; }
    }
}
